package pojos;
// Generated 3/10/2019 03:03:22 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Arl generated by hbm2java
 */
public class Arl  implements java.io.Serializable {


     private int idarl;
     private String nombre;
     private String telefono;
     private Set seguridadSocials = new HashSet(0);

    public Arl() {
    }

	
    public Arl(int idarl, String nombre, String telefono) {
        this.idarl = idarl;
        this.nombre = nombre;
        this.telefono = telefono;
    }
    public Arl(int idarl, String nombre, String telefono, Set seguridadSocials) {
       this.idarl = idarl;
       this.nombre = nombre;
       this.telefono = telefono;
       this.seguridadSocials = seguridadSocials;
    }
   
    public int getIdarl() {
        return this.idarl;
    }
    
    public void setIdarl(int idarl) {
        this.idarl = idarl;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Set getSeguridadSocials() {
        return this.seguridadSocials;
    }
    
    public void setSeguridadSocials(Set seguridadSocials) {
        this.seguridadSocials = seguridadSocials;
    }




}


