package pojos;
// Generated 3/10/2019 03:03:22 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Descuentos generated by hbm2java
 */
public class Descuentos  implements java.io.Serializable {


     private int iddescuentos;
     private String nombre;
     private int valor;
     private Set empleados = new HashSet(0);

    public Descuentos() {
    }

	
    public Descuentos(int iddescuentos, String nombre, int valor) {
        this.iddescuentos = iddescuentos;
        this.nombre = nombre;
        this.valor = valor;
    }
    public Descuentos(int iddescuentos, String nombre, int valor, Set empleados) {
       this.iddescuentos = iddescuentos;
       this.nombre = nombre;
       this.valor = valor;
       this.empleados = empleados;
    }
   
    public int getIddescuentos() {
        return this.iddescuentos;
    }
    
    public void setIddescuentos(int iddescuentos) {
        this.iddescuentos = iddescuentos;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getValor() {
        return this.valor;
    }
    
    public void setValor(int valor) {
        this.valor = valor;
    }
    public Set getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set empleados) {
        this.empleados = empleados;
    }




}


