package pojos;
// Generated 3/10/2019 03:03:22 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private int idempleado;
     private Descuentos descuentos;
     private SeguridadSocial seguridadSocial;
     private Vacaciones vacaciones;
     private String nombre;
     private String cargo;
     private Set nominas = new HashSet(0);
     private Set empresas = new HashSet(0);

    public Empleado() {
    }

	
    public Empleado(int idempleado, Descuentos descuentos, SeguridadSocial seguridadSocial, Vacaciones vacaciones, String nombre, String cargo) {
        this.idempleado = idempleado;
        this.descuentos = descuentos;
        this.seguridadSocial = seguridadSocial;
        this.vacaciones = vacaciones;
        this.nombre = nombre;
        this.cargo = cargo;
    }
    public Empleado(int idempleado, Descuentos descuentos, SeguridadSocial seguridadSocial, Vacaciones vacaciones, String nombre, String cargo, Set nominas, Set empresas) {
       this.idempleado = idempleado;
       this.descuentos = descuentos;
       this.seguridadSocial = seguridadSocial;
       this.vacaciones = vacaciones;
       this.nombre = nombre;
       this.cargo = cargo;
       this.nominas = nominas;
       this.empresas = empresas;
    }
   
    public int getIdempleado() {
        return this.idempleado;
    }
    
    public void setIdempleado(int idempleado) {
        this.idempleado = idempleado;
    }
    public Descuentos getDescuentos() {
        return this.descuentos;
    }
    
    public void setDescuentos(Descuentos descuentos) {
        this.descuentos = descuentos;
    }
    public SeguridadSocial getSeguridadSocial() {
        return this.seguridadSocial;
    }
    
    public void setSeguridadSocial(SeguridadSocial seguridadSocial) {
        this.seguridadSocial = seguridadSocial;
    }
    public Vacaciones getVacaciones() {
        return this.vacaciones;
    }
    
    public void setVacaciones(Vacaciones vacaciones) {
        this.vacaciones = vacaciones;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }
    public Set getNominas() {
        return this.nominas;
    }
    
    public void setNominas(Set nominas) {
        this.nominas = nominas;
    }
    public Set getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(Set empresas) {
        this.empresas = empresas;
    }




}


