package pojos;
// Generated 3/10/2019 03:03:22 AM by Hibernate Tools 4.3.1



/**
 * Empresa generated by hbm2java
 */
public class Empresa  implements java.io.Serializable {


     private int idempresa;
     private Empleado empleado;
     private Nomina nomina;
     private String nombre;
     private String cargo;

    public Empresa() {
    }

	
    public Empresa(int idempresa, Empleado empleado, Nomina nomina, String cargo) {
        this.idempresa = idempresa;
        this.empleado = empleado;
        this.nomina = nomina;
        this.cargo = cargo;
    }
    public Empresa(int idempresa, Empleado empleado, Nomina nomina, String nombre, String cargo) {
       this.idempresa = idempresa;
       this.empleado = empleado;
       this.nomina = nomina;
       this.nombre = nombre;
       this.cargo = cargo;
    }
   
    public int getIdempresa() {
        return this.idempresa;
    }
    
    public void setIdempresa(int idempresa) {
        this.idempresa = idempresa;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Nomina getNomina() {
        return this.nomina;
    }
    
    public void setNomina(Nomina nomina) {
        this.nomina = nomina;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }




}


