package pojos;
// Generated 3/10/2019 03:03:22 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Eps generated by hbm2java
 */
public class Eps  implements java.io.Serializable {


     private int ideps;
     private String nombre;
     private String direccion;
     private int numero;
     private Set seguridadSocials = new HashSet(0);

    public Eps() {
    }

	
    public Eps(int ideps, String nombre, String direccion, int numero) {
        this.ideps = ideps;
        this.nombre = nombre;
        this.direccion = direccion;
        this.numero = numero;
    }
    public Eps(int ideps, String nombre, String direccion, int numero, Set seguridadSocials) {
       this.ideps = ideps;
       this.nombre = nombre;
       this.direccion = direccion;
       this.numero = numero;
       this.seguridadSocials = seguridadSocials;
    }
   
    public int getIdeps() {
        return this.ideps;
    }
    
    public void setIdeps(int ideps) {
        this.ideps = ideps;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public int getNumero() {
        return this.numero;
    }
    
    public void setNumero(int numero) {
        this.numero = numero;
    }
    public Set getSeguridadSocials() {
        return this.seguridadSocials;
    }
    
    public void setSeguridadSocials(Set seguridadSocials) {
        this.seguridadSocials = seguridadSocials;
    }




}


