package pojos;
// Generated 3/10/2019 03:03:22 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Nomina generated by hbm2java
 */
public class Nomina  implements java.io.Serializable {


     private int idnomina;
     private Empleado empleado;
     private PeriodoDevengado periodoDevengado;
     private String total;
     private Set empresas = new HashSet(0);

    public Nomina() {
    }

	
    public Nomina(int idnomina, Empleado empleado, PeriodoDevengado periodoDevengado, String total) {
        this.idnomina = idnomina;
        this.empleado = empleado;
        this.periodoDevengado = periodoDevengado;
        this.total = total;
    }
    public Nomina(int idnomina, Empleado empleado, PeriodoDevengado periodoDevengado, String total, Set empresas) {
       this.idnomina = idnomina;
       this.empleado = empleado;
       this.periodoDevengado = periodoDevengado;
       this.total = total;
       this.empresas = empresas;
    }
   
    public int getIdnomina() {
        return this.idnomina;
    }
    
    public void setIdnomina(int idnomina) {
        this.idnomina = idnomina;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public PeriodoDevengado getPeriodoDevengado() {
        return this.periodoDevengado;
    }
    
    public void setPeriodoDevengado(PeriodoDevengado periodoDevengado) {
        this.periodoDevengado = periodoDevengado;
    }
    public String getTotal() {
        return this.total;
    }
    
    public void setTotal(String total) {
        this.total = total;
    }
    public Set getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(Set empresas) {
        this.empresas = empresas;
    }




}


