package pojos;
// Generated 3/10/2019 03:03:22 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Pensiones generated by hbm2java
 */
public class Pensiones  implements java.io.Serializable {


     private int idpensiones;
     private String nombre;
     private String direccion;
     private Set seguridadSocials = new HashSet(0);

    public Pensiones() {
    }

	
    public Pensiones(int idpensiones, String nombre, String direccion) {
        this.idpensiones = idpensiones;
        this.nombre = nombre;
        this.direccion = direccion;
    }
    public Pensiones(int idpensiones, String nombre, String direccion, Set seguridadSocials) {
       this.idpensiones = idpensiones;
       this.nombre = nombre;
       this.direccion = direccion;
       this.seguridadSocials = seguridadSocials;
    }
   
    public int getIdpensiones() {
        return this.idpensiones;
    }
    
    public void setIdpensiones(int idpensiones) {
        this.idpensiones = idpensiones;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Set getSeguridadSocials() {
        return this.seguridadSocials;
    }
    
    public void setSeguridadSocials(Set seguridadSocials) {
        this.seguridadSocials = seguridadSocials;
    }




}


