package pojos;
// Generated 3/10/2019 03:03:22 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PeriodoDevengado generated by hbm2java
 */
public class PeriodoDevengado  implements java.io.Serializable {


     private int idperiodoDevengado;
     private Date inicio;
     private Date corte;
     private int dias;
     private Set nominas = new HashSet(0);

    public PeriodoDevengado() {
    }

	
    public PeriodoDevengado(int idperiodoDevengado, Date inicio, Date corte, int dias) {
        this.idperiodoDevengado = idperiodoDevengado;
        this.inicio = inicio;
        this.corte = corte;
        this.dias = dias;
    }
    public PeriodoDevengado(int idperiodoDevengado, Date inicio, Date corte, int dias, Set nominas) {
       this.idperiodoDevengado = idperiodoDevengado;
       this.inicio = inicio;
       this.corte = corte;
       this.dias = dias;
       this.nominas = nominas;
    }
   
    public int getIdperiodoDevengado() {
        return this.idperiodoDevengado;
    }
    
    public void setIdperiodoDevengado(int idperiodoDevengado) {
        this.idperiodoDevengado = idperiodoDevengado;
    }
    public Date getInicio() {
        return this.inicio;
    }
    
    public void setInicio(Date inicio) {
        this.inicio = inicio;
    }
    public Date getCorte() {
        return this.corte;
    }
    
    public void setCorte(Date corte) {
        this.corte = corte;
    }
    public int getDias() {
        return this.dias;
    }
    
    public void setDias(int dias) {
        this.dias = dias;
    }
    public Set getNominas() {
        return this.nominas;
    }
    
    public void setNominas(Set nominas) {
        this.nominas = nominas;
    }




}


