package pojos;
// Generated 3/10/2019 03:03:22 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SeguridadSocial generated by hbm2java
 */
public class SeguridadSocial  implements java.io.Serializable {


     private int idseguridadSocial;
     private Arl arl;
     private Eps eps;
     private Pensiones pensiones;
     private Set empleados = new HashSet(0);

    public SeguridadSocial() {
    }

	
    public SeguridadSocial(int idseguridadSocial, Arl arl, Eps eps, Pensiones pensiones) {
        this.idseguridadSocial = idseguridadSocial;
        this.arl = arl;
        this.eps = eps;
        this.pensiones = pensiones;
    }
    public SeguridadSocial(int idseguridadSocial, Arl arl, Eps eps, Pensiones pensiones, Set empleados) {
       this.idseguridadSocial = idseguridadSocial;
       this.arl = arl;
       this.eps = eps;
       this.pensiones = pensiones;
       this.empleados = empleados;
    }
   
    public int getIdseguridadSocial() {
        return this.idseguridadSocial;
    }
    
    public void setIdseguridadSocial(int idseguridadSocial) {
        this.idseguridadSocial = idseguridadSocial;
    }
    public Arl getArl() {
        return this.arl;
    }
    
    public void setArl(Arl arl) {
        this.arl = arl;
    }
    public Eps getEps() {
        return this.eps;
    }
    
    public void setEps(Eps eps) {
        this.eps = eps;
    }
    public Pensiones getPensiones() {
        return this.pensiones;
    }
    
    public void setPensiones(Pensiones pensiones) {
        this.pensiones = pensiones;
    }
    public Set getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set empleados) {
        this.empleados = empleados;
    }




}


