package pojos;
// Generated 3/10/2019 03:03:22 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Vacaciones generated by hbm2java
 */
public class Vacaciones  implements java.io.Serializable {


     private int idvacaciones;
     private String empleado;
     private Date inicio;
     private Date fin;
     private int dias;
     private Set empleados = new HashSet(0);

    public Vacaciones() {
    }

	
    public Vacaciones(int idvacaciones, String empleado, Date inicio, Date fin, int dias) {
        this.idvacaciones = idvacaciones;
        this.empleado = empleado;
        this.inicio = inicio;
        this.fin = fin;
        this.dias = dias;
    }
    public Vacaciones(int idvacaciones, String empleado, Date inicio, Date fin, int dias, Set empleados) {
       this.idvacaciones = idvacaciones;
       this.empleado = empleado;
       this.inicio = inicio;
       this.fin = fin;
       this.dias = dias;
       this.empleados = empleados;
    }
   
    public int getIdvacaciones() {
        return this.idvacaciones;
    }
    
    public void setIdvacaciones(int idvacaciones) {
        this.idvacaciones = idvacaciones;
    }
    public String getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(String empleado) {
        this.empleado = empleado;
    }
    public Date getInicio() {
        return this.inicio;
    }
    
    public void setInicio(Date inicio) {
        this.inicio = inicio;
    }
    public Date getFin() {
        return this.fin;
    }
    
    public void setFin(Date fin) {
        this.fin = fin;
    }
    public int getDias() {
        return this.dias;
    }
    
    public void setDias(int dias) {
        this.dias = dias;
    }
    public Set getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set empleados) {
        this.empleados = empleados;
    }




}


